### ISSUE TITLE
"Install DHCP packages" does not work in tag v0.1.1

### ISSUE THREAD

**Issue by kiview** [debops/ansible-dhcpd#25]
Ansible will fail with the following error:
```
failed: [dhcp.foo.bar] (item=[u'dhcpd_base_packages_map[dhcpd_mode]']) => {"failed": true, "item": ["dhcpd_base_packages_map[dhcpd_mode]"], "msg": "No package(s) matching 'dhcpd_base_packages_map[dhcpd_mode]' available"}
```
This happens because `dhcpd_base_packages_map[dhcpd_mode]` as a plain string and not as an variable.

I wonder what this means for v0.1.1 (which I got from Ansible-Galaxy). Should I simply use the master branch (since this bug is fixed there) and avoid the tagged version?

**Comment by drybjed** [comment]
Thanks for the heads up. I'll release a new tagged version to fix this in Ansible Galaxy.

**Comment by drybjed** [comment]
@kiview The `v0.1.2` version is now on Ansible Galaxy. Can you check and close the issue if it's solved?

**Comment by kiview** [comment]
Thanks a lot, the role in Ansible Galaxy work now.
