### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by nicolepickle** [debops/ansible-dhcpd#34]
This play has a dependency on the debops.secret role which I no longer see here.  Can that repo be restored?

```
# Dependancy of Debops ansible-dhcpd
#- src: https://github.com/debops/ansible-secret.git
#  scm: git
#  version: "v0.3.1"
#  name: debops.secret

**Comment by drybjed** [comment]
This repository is no longer maintained, you should switch to using the [DebOps monorepo](https://github.com/debops/debops/) which has all the roles included. Please read [this FAQ entry](https://docs.debops.org/en/master/introduction/faq.html#i-installed-one-of-debops-roles-via-ansible-galaxy-but-it-doesn-t-work-why) and the [DebOps installation instructions](https://docs.debops.org/en/master/user-guide/install.html) for more details. At the moment installation of DebOps might not work correctly via Ansible Galaxy, you should install the repository directly instead.

**Comment by nicolepickle** [comment]
Thank you for this info!
